# tasks file for roles/proxy
- name: Login to Docker Hub
  community.docker.docker_login:
    username: "{{ dockerhub_username }}"
    password: "{{ dockerhub_token }}"

- name: Run HTTPD proxy container
  community.docker.docker_container:
    name: my_proxy
    image: "{{ dockerhub_username }}/tp-devops-httpd:latest"
    ports:
      - "80:80"
    networks:
      - name: app_network
    restart_policy: always
    state: started
